apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  serviceName: {{ .Values.postgres.serviceName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      name: {{ .Values.postgres.name }}
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      initContainers:
      - name: fix-disk-rights
        image: busybox
        command:
          - /bin/sh
          - -xec
          - chown -R 70:70 /var/lib/postgresql/data
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          imagePullPolicy: "Always"
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp
          readinessProbe:
            tcpSocket:
              port: tcp
          volumeMounts:
          - name: storage
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.storageSize }}          
